### PR TITLE
Note widget

### LINKED ISSUE #15: Create note widgit
Create a note widgit which:

* Opens upon clicking icon
* Upon opening has at textbox
* Will close upon clicking outside the widgit

We will set up integration with localStorage later

### PR DESCRIPTION
**Pull request by wjhurley**
I created the Note Widget trying to follow the same component structure and logic as the Weather Widget. I'm still struggling to wrap my head around Redux completely and was unsure of how to update the store with the value from the textarea, so I gave the NoteModal component it's own state and stored the textarea value there. I would greatly appreciate it if you could help to incorporate Redux to store the note. Closes #15.

### CODE REVIEW

**Comment by joshmorel** [comment]
I updated this so it works with redux. I did make some changes to convention for actions/reducers and will go back to do a (minor) refactor for weather after this PR is merged with master. 

I'll start on how to connect to redux, noting any changes made and why. Idea is that we have one state tree for the entire single-page app which can be accessed by any React component via the ``connect`` function. 

In building out components for the app, we're following [the convention](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) to divide components into **container components** and **presentational components**.

* Container components: essentially the widgets - "WeatherWidget.js", "NoteWidget.js" etc. These are aware of redux and use ``connect`` to access parts of the state tree and to dispatch actions. Their major concern is how things work.
* Presentational components: everything else which is "contained" within each "widget", for example "NoteIcon", "NoteModal". Their major concern is how things look.. They only have local state if it is UI related AND don't need access to localStorage, an async API, or are not affected by changes made within another widget/module. Examples include the arrow appearing on hover, or the clock update.

A few more notes (and one question):

* I also created **common** components which can be used to compose other components, with the goal of stylistic consistency and code re-use. I didn't do this for the weather icon arrow, because in the original Leoh it is only used for the weather widget. **My question - which of two options do we take**:
  * If you want to use it for other widgets, we should look to change that. 
  * Alternatively we can drop from the note widget and future widgets we work on to makes things a bit simpler and consistent with original..
* Each action type has to be unique so "TOGGLE_ICON_VISIBILITY" as a weather action is not good. Instead I'm following the convention "NOUN_VERB", for example "WEATHER_ICON_TOGGLE_VISIBILITY" as suggested [here](https://medium.com/@kylpo/redux-best-practices-eef55a20cc72)
* I started to use the constant for actionTypes as suggested [here](http://redux.js.org/docs/recipes/ReducingBoilerplate.html#actions)
* For each reducer file, I think it's simpler to have a single reducer instead of what I originally did which was using an intermediate ``combineReducers``

I'm going to refactor weather for the last 3 once we're both good with this PR.

**Comment by wjhurley** [comment]
I'll finish reviewing the code changes tomorrow, but I had a question about actionTypes.js. This line:
```
export const NOTE_CONTENT_UPDATE = 'NOTE_CONTENTS_UPDATE';
```
Should `'NOTE_CONTENTS_UPDATE'` be updated to `'NOTE_CONTENT_UPDATE'` to match the constant the string is being assigned to?

**Comment by joshmorel** [comment]
Yep it's a typo. Either of us can change it without any effect - once you start using constants its the constant that matters not the original string (each must be unique!). Some regression tests could help confirm that but I'd like to make sure we're set on the architecture before adding any.

**Comment by wjhurley** [comment]
Regarding your question about the icon arrow, I am fine with dropping it. I just thought it looked cool, so I added it to the note widget. If we did keep it and use that with the other widgets, I think we would either need to have two common components, one for icon arrow up and one for icon arrow down, or pass down the className from the parent component.

I have a question regarding the NoteModal:
I see that the NoteModal is aware of Redux, but in the convention you listed above, you stated that only the container component (NoteWidget) should be aware of Redux. Was there a reason that you chose to make the NoteModal aware of Redux rather than passing that state down from the NoteWidget as props?

**Comment by joshmorel** [comment]
Nah I'm fine with keeping it. 

For NoteModal that's my mistake - I had it there before but moved to widget so it's in both places incorrectly. Anyways, in doing some exploration for the onClickOutside I've figured out how to do it. By end of today I'd like to have this refactored on this branch and will re-commit. 

I'll provide a few more details in slack related to our paired work tomorrow.

**Comment by wjhurley** [comment]
I don't want to derail your refactoring or make you reconsider it, but I thought you might like to read this [article](https://reactrocket.com/post/react-redux-optimization/).

It makes a good point for having components such as the NoteModal aware of Redux, because using the container component convention NoteWidget has to rerender every time that there is a change to the state even though it is passing that state down to NoteModal.

**Comment by joshmorel** [comment]
Good find. I do agree that the architecture is not quite right at this point... but not necessarily for optimization reasons (the widget only renders the icon as well as the modal... so optimization at this point is not really an issue but that doesn't mean better understanding of `connect` is not a good thing! ).

The issue is more so re-usability. For example, having a separate NoteModal, WeatherModal, NewsModal each with their own css file seems like an indication of something wrong. Perhaps there should be one common Modal and one Icon, which each of the apps' **modules / container components** can use and plug it's own properties into.

I'm not really sure the best answer which is why I've been experimenting with different set-ups. But at the same time... perhaps the most important thing is getting something working even if the architecture is less than good  --- the app is only so big and we can always refactor for elegance/optimization later once we understand more.

So I've committed changes to at least make the Note more consistent - having the NoteModal disconnected from redux. We can either:

1. merge into master and move onto another module
1. merge into master and refactor the architecture
1. further refactor in this branch - but we'd need to refactor everything not just note

I'm for either of the first 2 options. If we refactor we need to refactor also common and weather at the same time so it should be done in another branch.

**Comment by wjhurley** [comment]
I'm fine with option 1. Like you said, I think it's more important we push ahead and get this working rather than worrying about the architecture right now. I am building a common IconArrow component on the todo-widget branch for both NoteWidget and TodoWidget to use.

**Pull request merged**
